//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.NguoiDan.DangKyBienDong {
    
    
    public partial class ucDeNghiCapLai {
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// txtSoVaoSoCapGCN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSoVaoSoCapGCN;
        
        /// <summary>
        /// txtSoPhatHanhGCN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSoPhatHanhGCN;
        
        /// <summary>
        /// txtNgayCapGCN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNgayCapGCN;
        
        /// <summary>
        /// txtLyDoBienDong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtLyDoBienDong;
        
        /// <summary>
        /// ucThongTinThuaDatCoThayDoiDoDoDacLai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DMCWeb.NguoiDan.DangKyBienDong.ucThongTinThuaDatCoThayDoiDoDoDacLai ucThongTinThuaDatCoThayDoiDoDoDacLai;
        
        /// <summary>
        /// ucThongTinTaiSanGanLienVoiDatDaCapGCNCoThayDoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DMCWeb.NguoiDan.DangKyBienDong.ucThongTinTaiSanGanLienVoiDatDaCapGCNCoThayDoi ucThongTinTaiSanGanLienVoiDatDaCapGCNCoThayDoi;
        
        /// <summary>
        /// txtGiayToLienQuan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtGiayToLienQuan;
        
        /// <summary>
        /// btnLuuThongTinKeKhai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLuuThongTinKeKhai;
        
        /// <summary>
        /// btnSuaThongTinKeKhai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSuaThongTinKeKhai;
    }
}
