//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.NguoiDan.DangKyBienDong {
    
    
    public partial class ucDeNghiTachThua_HopThua {
        
        /// <summary>
        /// Tach_HopThua control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DMCWeb.NguoiDan.DangKyBienDong.Tach_HopThua Tach_HopThua;
        
        /// <summary>
        /// txtLyDoTachHopThua control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtLyDoTachHopThua;
        
        /// <summary>
        /// txtGiayToLienQuan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtGiayToLienQuan;
        
        /// <summary>
        /// btnLuuThongTinKeKhai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLuuThongTinKeKhai;
        
        /// <summary>
        /// btnSuaThongTinKeKhai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSuaThongTinKeKhai;
    }
}
