//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMCWebEntities : DbContext
    {
        public DMCWebEntities()
            : base("name=DMCWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DVHCtam> DVHCtams { get; set; }
        public virtual DbSet<tblCayLauNam> tblCayLauNams { get; set; }
        public virtual DbSet<tblCayLauNamDuBi> tblCayLauNamDuBis { get; set; }
        public virtual DbSet<tblChu> tblChus { get; set; }
        public virtual DbSet<tblChuDangKyBienDong> tblChuDangKyBienDongs { get; set; }
        public virtual DbSet<tblChuDangKyBienDongDuBi> tblChuDangKyBienDongDuBis { get; set; }
        public virtual DbSet<tblChuDuBi> tblChuDuBis { get; set; }
        public virtual DbSet<tblChuHoSo> tblChuHoSoes { get; set; }
        public virtual DbSet<tblChuHoSoDuBi> tblChuHoSoDuBis { get; set; }
        public virtual DbSet<tblDoanhNghiep> tblDoanhNghieps { get; set; }
        public virtual DbSet<tblDonXinDangKyBienDongDuBi> tblDonXinDangKyBienDongDuBis { get; set; }
        public virtual DbSet<tblHoSo> tblHoSoes { get; set; }
        public virtual DbSet<tblHoSoBienDong> tblHoSoBienDongs { get; set; }
        public virtual DbSet<tblHoSoKeKhai> tblHoSoKeKhais { get; set; }
        public virtual DbSet<tblHoSoKeKhaiDuBi> tblHoSoKeKhaiDuBis { get; set; }
        public virtual DbSet<tblHoSoKeKhaiDuocChapNhan> tblHoSoKeKhaiDuocChapNhans { get; set; }
        public virtual DbSet<tblLoaiDeNghiDangKyCapGCN> tblLoaiDeNghiDangKyCapGCNs { get; set; }
        public virtual DbSet<tblLoaiNhaO_CongTrinh> tblLoaiNhaO_CongTrinh { get; set; }
        public virtual DbSet<tblNguonGocSuDung> tblNguonGocSuDungs { get; set; }
        public virtual DbSet<tblRungSanXuatLaRungTrong> tblRungSanXuatLaRungTrongs { get; set; }
        public virtual DbSet<tblRungSanXuatLaRungTrongDuBi> tblRungSanXuatLaRungTrongDuBis { get; set; }
        public virtual DbSet<tblThongTinNhaO> tblThongTinNhaOs { get; set; }
        public virtual DbSet<tblThongTinNhaODuBi> tblThongTinNhaODuBis { get; set; }
        public virtual DbSet<tblThongTinTaiSanGanLienVoiDatTrongBienDong> tblThongTinTaiSanGanLienVoiDatTrongBienDongs { get; set; }
        public virtual DbSet<tblThongTinTaiSanGanLienVoiDatTrongBienDongDuBi> tblThongTinTaiSanGanLienVoiDatTrongBienDongDuBis { get; set; }
        public virtual DbSet<tblThuaDat> tblThuaDats { get; set; }
        public virtual DbSet<tblThuaDatDeNghiHopThuaTrongBienDong> tblThuaDatDeNghiHopThuaTrongBienDongs { get; set; }
        public virtual DbSet<tblThuaDatDeNghiHopThuaTrongBienDongTheoDon> tblThuaDatDeNghiHopThuaTrongBienDongTheoDons { get; set; }
        public virtual DbSet<tblThuaDatDeNghiTachThuaTrongBienDong> tblThuaDatDeNghiTachThuaTrongBienDongs { get; set; }
        public virtual DbSet<tblThuaDatDeNghiTachThuaTrongBienDongTheoDon> tblThuaDatDeNghiTachThuaTrongBienDongTheoDons { get; set; }
        public virtual DbSet<tblThuaDatDuBi> tblThuaDatDuBis { get; set; }
        public virtual DbSet<tblThuaDatThayDoiTrongBienDong> tblThuaDatThayDoiTrongBienDongs { get; set; }
        public virtual DbSet<tblThuaDatThayDoiTrongBienDongDuBi> tblThuaDatThayDoiTrongBienDongDuBis { get; set; }
        public virtual DbSet<tblXacNhanCapCoSo> tblXacNhanCapCoSoes { get; set; }
        public virtual DbSet<tblXacNhanCapCoSoVeBienDong> tblXacNhanCapCoSoVeBienDongs { get; set; }
        public virtual DbSet<tblXacNhanCoQuanDangKyDatDai> tblXacNhanCoQuanDangKyDatDais { get; set; }
        public virtual DbSet<tblYKienCoQuanDangKyDatDaiVeBienDong> tblYKienCoQuanDangKyDatDaiVeBienDongs { get; set; }
        public virtual DbSet<tblYKienCoQuanTaiNguyenVaMoiTruongVeBienDong> tblYKienCoQuanTaiNguyenVaMoiTruongVeBienDongs { get; set; }
        public virtual DbSet<tblDonXinDangKyBienDong> tblDonXinDangKyBienDongs { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
