//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChuDuBi
    {
        public long MaChu { get; set; }
        public string DanhXung { get; set; }
        public string HoTen { get; set; }
        public string NamSinh { get; set; }
        public string DiaChi { get; set; }
        public string DinhDanh { get; set; }
        public string SoDinhDanh { get; set; }
        public string NoiCap { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string QuocTich { get; set; }
    }
}
