//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCayLauNam
    {
        public long ID { get; set; }
        public Nullable<long> MaHoSo { get; set; }
        public string LoaiCayChuYeu { get; set; }
        public string DienTich { get; set; }
        public string SoHuuChung { get; set; }
        public string SoHuuRieng { get; set; }
        public string ThoiHanSoHuu { get; set; }
    }
}
