//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoanhNghiep
    {
        public long MaToChuc { get; set; }
        public string TenToChuc { get; set; }
        public string QuyetDinhThanhLap { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public string CoQuanQuyetDinh { get; set; }
        public string GiayDangKyKinhDoanhSo { get; set; }
        public Nullable<System.DateTime> NgayBatDauCoHieuLuc { get; set; }
        public string CoQuanKyGiayPhep { get; set; }
        public string GiayPhepDauTuSo { get; set; }
        public Nullable<System.DateTime> NgayGiayPhepCoHieuLuc { get; set; }
        public string CoQuanCapGIayPhep { get; set; }
    }
}
