//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonXinDangKyBienDong
    {
        public long MaDangKyBienDong { get; set; }
        public string NguoiVietDon { get; set; }
        public Nullable<System.DateTime> NgayVietDon { get; set; }
        public string SoVaoSoCapGCN { get; set; }
        public string SoPhatHanhGCN { get; set; }
        public Nullable<System.DateTime> NgayCapGCN { get; set; }
        public string BienDongVe { get; set; }
        public string NoiDungGhiTrenGCNTruocKhiBienDong { get; set; }
        public string NoiDungSauKhiBienDong { get; set; }
        public string LyDoBienDong { get; set; }
        public string TinhHinhThucHienNghiaVuTaiChinh { get; set; }
        public string GiayToKemTheo { get; set; }
        public string LoaiBienDong { get; set; }
        public string LoaiDoiTuongApDung { get; set; }
        public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
        public string NguoiNhanHoSo { get; set; }
        public string SoTiepNhan { get; set; }
        public string Quyen { get; set; }
        public string KinhGuiCoQuanChucNang { get; set; }
        public string DonViHanhChinh { get; set; }
    }
}
