//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSoKeKhaiDuocChapNhan
    {
        public long ID { get; set; }
        public Nullable<long> MaHoSoKeKhai { get; set; }
        public Nullable<long> MaHoSoKeKhaiDuBi { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
    }
}
