//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSoKeKhaiDuBi
    {
        public long MaHoSoKeKhai { get; set; }
        public string KinhGuiCoQuanChucNang { get; set; }
        public Nullable<System.DateTime> NgayNhanHoSo { get; set; }
        public string NguoiNhanHoSo { get; set; }
        public string SoTiepNhan { get; set; }
        public string Quyen { get; set; }
        public string NguoiVietDon { get; set; }
        public string DonViHanhChinh { get; set; }
        public string GiayToKemTheo { get; set; }
        public string NghiaVuTaiChinh { get; set; }
        public string DeNghiKhac { get; set; }
        public string SoDienThoaiLienHe { get; set; }
        public string DiaChiMail { get; set; }
        public string MaLoaiDeNghi { get; set; }
        public string MaLoaiDoiTuong { get; set; }
        public string TongSoThuaDat { get; set; }
        public Nullable<bool> DaGuiDi { get; set; }
    }
}
