//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSo
    {
        public long MaHoSo { get; set; }
        public Nullable<long> TongSoThua { get; set; }
        public string LoaiDoiTuong { get; set; }
        public string DonViHanhChinh { get; set; }
        public string TrangThaiHoSoCapGCN { get; set; }
    }
}
