//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongTinNhaODuBi
    {
        public long MaNhaO { get; set; }
        public Nullable<long> MaHoSoKeKhai { get; set; }
        public string LoaiNhaO { get; set; }
        public string DienTichXayDung { get; set; }
        public string DienTichSan { get; set; }
        public string SoHuuChung { get; set; }
        public string SoHuuRieng { get; set; }
        public string KetCau { get; set; }
        public string SoTang { get; set; }
        public Nullable<bool> CoHanCheThoiHanSoHuu { get; set; }
        public string ThoiHanSoHuu { get; set; }
    }
}
