//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongTinTaiSanGanLienVoiDatTrongBienDongDuBi
    {
        public long ID { get; set; }
        public Nullable<long> MaDangKyBienDong { get; set; }
        public string LoaiTaiSan { get; set; }
        public string DienTichXayDung { get; set; }
        public string DienTichSan { get; set; }
        public string NoiDungThayDoi { get; set; }
        public string LoaiTaiSanMoi { get; set; }
        public string DienTichXayDungMoi { get; set; }
        public string DienTichSanMoi { get; set; }
        public string NoiDungThayDoiMoi { get; set; }
    }
}
