//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThuaDatThayDoiTrongBienDongDuBi
    {
        public long ID { get; set; }
        public Nullable<long> MaThuaDat { get; set; }
        public Nullable<long> MaDangKyBienDong { get; set; }
        public string ToBanDo { get; set; }
        public string SoThua { get; set; }
        public string DienTich { get; set; }
        public string NoiDungThayDoiKhac { get; set; }
        public string ToBanDoMoi { get; set; }
        public string SoThuaMoi { get; set; }
        public string DienTichMoi { get; set; }
        public string NoiDungThayDoiKhacMoi { get; set; }
    }
}
