//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThuaDat
    {
        public long MaThuaDat { get; set; }
        public Nullable<long> MaHoSo { get; set; }
        public string ToBanDo { get; set; }
        public string SoThua { get; set; }
        public string DiaChi { get; set; }
        public string DienTich { get; set; }
        public string SuDungChung { get; set; }
        public string SuDungRieng { get; set; }
        public string MucDichSuDung { get; set; }
        public string ThoiHanSuDung { get; set; }
        public Nullable<System.DateTime> NgayBatDauSuDung { get; set; }
        public string LoaiNguonGocSuDung { get; set; }
        public string CoHanCheSuDung { get; set; }
        public string NoiDungHanCheSuDung { get; set; }
    }
}
