//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThuaDatDeNghiTachThuaTrongBienDongTheoDon
    {
        public long ID { get; set; }
        public Nullable<long> MaDangKyBienDong { get; set; }
        public Nullable<long> MaThuaDat { get; set; }
        public string ToBanDo { get; set; }
        public string SoThua { get; set; }
        public string DiaChi { get; set; }
        public string SoPhatHanhGCN { get; set; }
        public string SoVaoSoCapGCN { get; set; }
        public Nullable<System.DateTime> NgayCapGCN { get; set; }
        public string SoThuaConDeNghiTach { get; set; }
        public string DienTichCon1 { get; set; }
        public string DienTichCon2 { get; set; }
    }
}
