//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXacNhanCapCoSoVeBienDong
    {
        public long ID { get; set; }
        public Nullable<long> MaDangKyBienDong { get; set; }
        public string NoiDungXacNhan { get; set; }
        public string NoiDungKhac { get; set; }
        public Nullable<System.DateTime> DiaChinh_NgayXacNhan { get; set; }
        public string DiaChinh_CanBo { get; set; }
        public string DiaChinh_TieuDeKy { get; set; }
        public Nullable<System.DateTime> UBND_NgayKy { get; set; }
        public string UBND_TieuDeKy { get; set; }
        public string UBND_NguoiKy { get; set; }
    }
}
