//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYKienCoQuanDangKyDatDaiVeBienDong
    {
        public long ID { get; set; }
        public Nullable<long> MaDangKyBienDong { get; set; }
        public string NoiDungYKien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string NguoiKiemTra { get; set; }
        public string ChucVuNguoiKiemTra { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string GiamDoc { get; set; }
    }
}
